language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: f8520074e28e394704faacb56000979d5d3348ed # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master